baseURL = 'https://stately-kataifi-98f27b.netlify.app/'
languageCode = 'en'
title = 'Drogheda Life'
theme = 'example-one'

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "News"
    pre = "pen-tool"
    url = "/news/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true    